import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";

import "./globals.css";
import MuiProvider from '../components/MuiProvider';
import FloatingWhatsAppButton from '../components/FloatingWhatsAppButton';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
  <body className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased`} style={{ background: '#F9F9F9', color: '#1A1A1A' }}>
        <MuiProvider>
          {children}
          <FloatingWhatsAppButton />
        </MuiProvider>
      </body>
    </html>
  );
}
