import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { ThemeProvider, CssBaseline } from '@mui/material';
import theme from '../theme';
import FloatingWhatsAppButton from '../components/FloatingWhatsAppButton';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ background: '#F9F9F9', color: '#1A1A1A' }}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          {children}
          <FloatingWhatsAppButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
